spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
